# Generated by Django 5.0.1 on 2024-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numDossier', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('sexe', models.CharField(max_length=2)),
                ('age', models.IntegerField()),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('diagnostic', models.TextField()),
                ('cure1', models.TextField()),
                ('cure2', models.TextField()),
                ('cure3', models.TextField()),
                ('cure4', models.TextField()),
                ('cure5', models.TextField()),
                ('bilan', models.TextField()),
                ('defrenation', models.TextField()),
                ('examComp', models.TextField()),
                ('resume', models.TextField()),
                ('dateRdv', models.DateTimeField(verbose_name='Date du bilan')),
            ],
        ),
    ]
