# Generated by Django 5.0.1 on 2024-01-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0002_rename_nom_dossiermedical_identite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='bilan1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='bilan10',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='bilan2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='bilan3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='bilan4',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='bilan5',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='bilan6',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='bilan7',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='bilan8',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='bilan9',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='cure1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='cure2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='cure3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='cure4',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='cure5',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='defrenation1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='defrenation2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='defrenation3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='defrenation4',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='defrenation5',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='examComp1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='examComp10',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='examComp2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='examComp3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='examComp4',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='examComp5',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='examComp6',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='examComp7',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='examComp8',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='examComp9',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='resume',
            field=models.TextField(null=True),
        ),
    ]
