# Generated by Django 5.0.1 on 2024-02-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0005_alter_dossiermedical_daterdv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossiermedical',
            old_name='defrenation4',
            new_name='antecedent',
        ),
        migrations.RenameField(
            model_name='dossiermedical',
            old_name='defrenation5',
            new_name='consigne',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='diagnostic',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='activiteCumule',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='ageDecouverte',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='carcinome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='circonstance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='clasM',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='clasN',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='clasT',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure10',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure6',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure7',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure8',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure9',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='metastase',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='nbrCure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='risque',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='stade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='totalChir',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='typeHisto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
