# Generated by Django 5.0.1 on 2024-02-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0006_rename_defrenation4_dossiermedical_antecedent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='activiteCumule',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='nbrCure',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
