# Generated by Django 5.0.1 on 2024-02-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0008_alter_dossiermedical_activitecumule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='anteFamiliaux',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='effraCapsulaire',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='embonVasculaire',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='multifoc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='refrac',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='thera',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
